import { readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const dir = join(import.meta.dirname, '..', 'public', 'logos')
const files = readdirSync(dir)

const manifest: Record<string, { ext: string; hasMark: boolean }> = {}

for (const f of files) {
  const match = f.match(/^(.+)\.(svg|png)$/)
  if (!match || f.includes('-mark')) continue
  const slug = match[1]!
  const ext = match[2]!
  const hasMark = files.includes(`${slug}-mark.svg`)
  manifest[slug] = { ext, hasMark }
}

const sorted = Object.fromEntries(
  Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b))
)

const output = `// Auto-generated by scripts/generate-logo-manifest.ts — do not edit manually
export const logoManifest: Record<
  string,
  { ext: 'svg' | 'png'; hasMark: boolean }
> = ${JSON.stringify(sorted, null, 2)} as const
`

writeFileSync(
  join(import.meta.dirname, '..', 'src', 'data', 'logo-manifest.ts'),
  output
)

console.log(
  `Generated manifest with ${Object.keys(sorted).length} entries (${Object.values(sorted).filter(v => v.hasMark).length} with marks)`
)
